module.exports = TYPES = {
    KEYWORD: "KEYWORD",
    PUNCTUATOR: "PUNCTUATOR",
    INTEGER: "INTEGER",
    STRING: "STRING",
    VARIABLE: "VARIABLE",
    OPERATOR: "OPERATOR",
    BOOLEAN: "BOOLEAN",
    CALL: "CALL",
    BINARY: "BINARY",
    ASSIGNMENT: "ASSIGNMENT",
    SEQUENCE: "SEQUENCE",
    NEGATION: "NEGATION"
};